FIX Members minimal CMS access were previously stuck in a login loop, now redirects to MFA
silverstripe/silverstripe-mfa pull request #375
Opened 2020-03-23 01:44 UTC by robbieaverill

Fixes https://github.com/silverstripe/silverstripe-mfa/issues/369 for SS 4

This allows https://github.com/silverstripe/silverstripe-admin/blob/1/code/LeftAndMain.php#L1007-L1010 to not return an empty list during MFA enabled login flows.

2020-03-25 22:05 UTC, Cheddam requested changes
Looks good! One recommendation to use a core API instead of replicating it.

Tested locally, and a user with access only to the Jobs admin is now successfully redirected to the MFA flow, although the unpatched behaviour is different to what I expected - the user was logged in immediately, rather than getting stuck in a loop. A community member also [reported seeing this behaviour](https://silverstripe-users.slack.com/archives/C36U3BDHN/p1585156903001100) this morning.

Let's get this patch merged and released ASAP to resolve both possible scenarios.

2020-03-25 22:05 UTC, Cheddam commented on src/Service/EnforcementManager.php
> +    protected function withMember(Member $member, Closure $callback)
This could be replaced with [`Member::actAs()`](https://github.com/silverstripe/silverstripe-framework/blob/4/src/Security/Member.php#L803)

2020-03-25 23:07 UTC, robbieaverill commented on src/Service/EnforcementManager.php
> +    protected function withMember(Member $member, Closure $callback)
Oh good call, I thought this was part of SapphireTest

2020-03-25 23:23 UTC, robbieaverill commented
Thanks for the review @Cheddam, I've made your changes. I haven't tested it though.

2020-03-26 00:34 UTC, Cheddam approved these changes
Manually tested again, looking good. Thanks!

2020-03-26 00:34 UTC, merged

2020-03-26 00:53 UTC, robbieaverill commented
No worries, hopefully this bug never comes back again