FIX Explicitly disable browser cache on verification response
silverstripe/silverstripe-mfa pull request #417
Opened 2021-01-13 22:34 UTC by emteknetnz

Fixes https://github.com/silverstripe/silverstripe-mfa/issues/414

May fix https://github.com/silverstripe/silverstripe-mfa/issues/393 (untested)

2021-01-25 02:05 UTC, maxime-rainville requested changes
Is there a practical way of writing a unit test for this?

2021-01-26 02:50 UTC, emteknetnz commented
I've added a unit test for this

2021-01-26 21:26 UTC, maxime-rainville requested changes
Looks good. I think we should explicitly say what the test is asserting otherwise the nekt person who looks at this will be very confused.

2021-01-26 21:26 UTC, maxime-rainville commented on tests/php/Authenticator/LoginHandlerTest.php
> +        $this->assertSame('disabled', $middleware->getState());
```suggestion
        $this->assertSame('disabled', $middleware->getState(), 'startVerification disables cache on HTTPCacheControlMiddleware so challenges never get cached');
```

2021-01-26 21:34 UTC, emteknetnz commented
@maxime-rainville I've added some comments explaining what we're testing

2021-01-27 03:12 UTC, maxime-rainville approved these changes
Looks good.

2021-01-27 03:12 UTC, merged